# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e906db3ce2a9a631dc3a015634643bb0"
name = "Meta bulk assign"
application_url = "https://meta-bulk-assign.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_files,read_metaobject_definitions,write_metaobjects"

[auth]
redirect_urls = [
  "https://meta-bulk-assign.vercel.app/api/auth",
  "https://meta-bulk-assign.vercel.app/api/auth/callback"
]
